name = "ALPINEExplorer"
uuid = "375ebf2c-188c-48b0-9e4f-a990124af1d6"
authors = ["Nicholas Minor <nrminor@wisc.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
